# Site settings
title: Joel Carlson!
email: Joelcarlson@snu.ac.kr
description: "This is Joel Carlson's website.  I am an MSc student at Seoul National University in the Biomedical Radiation Science program.  I am currently studying monte carlo methods for brachytherapy dosimetry.  Outside of dosimetry I am also interested in radiobiology and radiogenomics.  Most recently I have been learning to use R for data analysis, and exploring packages such as shiny to move my work online."
minidescription: "Joel Carlson, MSc student at Seoul National University.  Get in touch via email or github!"
footertitle: Joel Carlson
baseurl: ""
url: "http://localhost:4000"
username: joelcarlson

# Build settings
markdown: kramdown
permalink: pretty
