# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joel Carlson
tagline:          'MSc student, Seoul National University'
description:      'A place for thoughts and projects'
url:              http://joelcarlson.github.io

author:
  name:           'Joel Carlson'
  url:            http://joelcarlson.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/joelcarlson

collections:
  research:
    output: true
    permalink: /research/:path/
  reproducible:
    output: true
    permalink: /reproducible/:path/



